apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: quarkust 
  janus-idp.io/tekton: quarkust
  backstage.io/kubernetes-id: quarkust
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: quarkust
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  